[features]
seeds = false
skip-lint = false
[programs.localnet]
collabs = "4HYr7M3ytiSoqr3Zh3iK1VcNNm7ZgrNikwmWYJdGMvw4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/anonymous/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
